version: "1.0"

general:
  buildTool: custom

stages:
  Build:
    steps:
      - script:
          name: "PoC - GitHub Source Pipeline"
          script: |
            echo "Pipeline executado com sucesso no SAP CI&D"
            echo "Repositorio SOURCE clonado corretamente"
            echo "Branch: ${GIT_BRANCH}"
